pipelines:
  pull-requests:
    '**':
      - parallel:
        - step:
            name: 'PHP coding standards checker'
            image: wodby/drupal-php:8.1-dev-4.37.6
            caches:
             - composer
            script:
              - cd docker4drupal
              - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s
              - composer install
              - export PATH="`pwd`/bin:$PATH"
              - ./vendor/bin/phpcs --report=checkstyle --standard=Drupal,DrupalPractice ./web/modules/custom | reviewdog -f=checkstyle -reporter=bitbucket-code-report -fail-on-error -filter-mode=nofilter -tee

        - step:
            name: 'JS coding standards checker'
            image: wodby/drupal-php:8.1-dev-4.37.6
            caches:
              - npm
              - yarn
              - composer  
            script:
              - sudo apk add nodejs
              - sudo apk add npm
              - npm install yarn
              - cd docker4drupal
              - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s
              - composer install
              - yarn add --dev eslint-config-drupal-bundle eslint
              - export PATH="`pwd`/bin:$PATH"
              - yarn eslint ./web/modules/custom ./web/themes/custom ./web/profiles/custom --no-error-on-unmatched-pattern | reviewdog -f=eslint -reporter=bitbucket-code-report -fail-on-error -filter-mode=nofilter -tee

definitions:
  caches:
    npm: ~/.npm/_cacache
    yarn: ~/.cache/yarn/v6
